version: "3"
services:
  node-app: 
    container_name: express-node-app-container
    ports: 
      - "4000:4000"
    env_file:
      - ./.env

  mongo:
   image: mongo
   restart: always
   volumes:
    - mongo-db:/data/db #Named volume
   environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: example    

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
  redis:
    image: redis

volumes:
  mongo-db: 